- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: ./cargo-foreach.sh fmt
  language: system
  types: [rust]
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: ./cargo-foreach.sh check
  language: system
  types: [rust]
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: ./cargo-foreach.sh clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
